CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating star_rating NOT NULL
);

INSERT INTO bookmarks (title, url, description, rating)
VALUES
('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', '5'),
('Google', 'https://www.google.com', 'Where we find everything else', '4'),
('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation', '5');

